### ISSUE TITLE
Building entrance showed where there should be no data

### ISSUE THREAD

**Issue by tigerfoot** [tigerfoot/geojson-angular-leaflet#1]
![screenshot_20160309_172359](https://cloud.githubusercontent.com/assets/788864/13642214/e3d3b04a-e61b-11e5-916b-8c2033568c56.png)
![screenshot_20160309_172435](https://cloud.githubusercontent.com/assets/788864/13642213/e3d1377a-e61b-11e5-8846-7bec0a98c934.png)
![screenshot_20160309_150550](https://cloud.githubusercontent.com/assets/788864/13642215/e3d8ff8c-e61b-11e5-9583-04fe7968e198.png)

Open demo search Les Esserts 4, Cortébert 
between building 2,4 there's some entrance shown (square as code_valide = 1)

But if the data are opened in qgis there's no data at that postion
(qgis center on 574550.8, 226266.1 project CRS EPSG:21791)

?
@Jenselme an idea ?

**Comment by Jenselme** [comment]
This comes from the layer `'nomdelieu.json'` which shouldn't be displayed.
